volumes:
  pg_data:
  static:
  media:

services:
  food_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: disciplina666/foodgram_backend
    env_file: .env
    depends_on:
      - food_db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: disciplina666/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: disciplina666/foodgram_gateway
    volumes:
       - static:/staticfiles
       - media:/app/media
    ports:
      - 9000:80
    depends_on:
      - backend
    restart: always