# Generated by Django 3.2.16 on 2025-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="recepts", verbose_name="Изображение"),
                ),
                ("description", models.TextField(verbose_name="Описание рецепта")),
                (
                    "cooking_time",
                    models.IntegerField(verbose_name="Время приготовления"),
                ),
            ],
        ),
    ]
