# Generated by Django 4.2 on 2025-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recept", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                default="default_tag_slug",
                max_length=32,
                unique=True,
                verbose_name="SLUG",
            ),
            preserve_default=False,
        ),
    ]
