# Generated by Django 4.2.23 on 2025-07-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recept",
            "0003_ingredient_recipe_recipeingredient_tag_delete_recept_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
