# Generated by Django 4.2.23 on 2025-07-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recept", "0004_rename_description_recipe_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="user",
            new_name="author",
        ),
    ]
