# Generated by Django 4.2 on 2025-07-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recept", "0005_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["id"],
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
