# Generated by Django 4.2.23 on 2025-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recept", "0007_shoppingcart"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
