# Generated by Django 4.2.23 on 2025-07-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recept", "0009_alter_favorite_options_alter_shoppingcart_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("slug", models.SlugField(max_length=32, null=True, unique=True)),
            ],
        ),
    ]
