# Generated by Django 4.2 on 2025-07-31 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_follow_following_alter_follow_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(254)],
                verbose_name="Электронная почта",
            ),
        ),
    ]
