# Generated by Django 4.2.23 on 2025-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Изображение пользователя",
            ),
        ),
    ]
