# Generated by Django 4.2 on 2025-07-31 21:45

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "Пользователь с таким именем уже существует."
                },
                help_text="Обязательное поле. 150 символов или меньше. Только буквы, цифры и @/./+/-/_ символы.",
                max_length=150,
                unique=True,
                validators=[
                    users.validators.validate_username,
                    django.core.validators.RegexValidator(
                        message="Имя пользователя может содержать только буквы, цифры и символы @/./+/-/_",
                        regex="^[\\w.@+-]+$",
                    ),
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
